//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatUserDetalle
    {
        public int ID { get; set; }
        public string connection_id { get; set; }
        public string user_cve { get; set; }
        public string user_nom { get; set; }
        public string mail { get; set; }
    }
}
