//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class otsdmov
    {
        public int num_OTS { get; set; }
        public string tipo_OTS { get; set; }
        public int num_reng { get; set; }
        public string tip_proceso { get; set; }
        public string nom_proceso { get; set; }
        public string descrip { get; set; }
        public string dificultad { get; set; }
        public Nullable<System.DateTime> fec_ini { get; set; }
        public System.DateTime fec_fin { get; set; }
        public string id_user { get; set; }
        public string error { get; set; }
        public string solucion { get; set; }
        public string obs { get; set; }
        public Nullable<short> clasificacion { get; set; }
        public string status { get; set; }
        public string aplica_para { get; set; }
    }
}
