//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class otsdcatlgos
    {
        public otsdcatlgos()
        {
            this.otscatlgos = new HashSet<otscatlgos>();
        }
    
        public string cve_catlgo { get; set; }
        public string nom_catlgo { get; set; }
        public string descripcion { get; set; }
        public short status { get; set; }
        public System.DateTime fec_ultact { get; set; }
    
        public virtual ICollection<otscatlgos> otscatlgos { get; set; }
    }
}
