//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class otsemov
    {
        public int num_OTS { get; set; }
        public string tipo_OTS { get; set; }
        public string ss_cve { get; set; }
        public string userAsig { get; set; }
        public string operacion { get; set; }
        public string userResp { get; set; }
        public string sts_prog { get; set; }
        public string descripcion { get; set; }
        public System.DateTime fec_asig { get; set; }
        public Nullable<System.DateTime> fec_fin { get; set; }
        public string aplica { get; set; }
        public string tipo_OTSP { get; set; }
        public Nullable<int> num_OTSP { get; set; }
        public string nomImg { get; set; }
        public Nullable<System.DateTime> fec_prom { get; set; }
    
        public virtual usuarios usuarios { get; set; }
        public virtual usuarios usuarios1 { get; set; }
    }
}
