//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class paros
    {
        public int num_OTS { get; set; }
        public string tipo_OTS { get; set; }
        public short num_reng { get; set; }
        public short sub_reng { get; set; }
        public System.DateTime fec_ini { get; set; }
        public Nullable<System.DateTime> fec_fin { get; set; }
        public string Motivo { get; set; }
        public short Sw_activo { get; set; }
    }
}
