//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarios
    {
        public usuarios()
        {
            this.otsemov = new HashSet<otsemov>();
            this.otsemov1 = new HashSet<otsemov>();
            this.rolesxUsr = new HashSet<rolesxUsr>();
        }
    
        public string user_cve { get; set; }
        public string nombre { get; set; }
        public string password { get; set; }
        public string mail { get; set; }
        public Nullable<System.DateTime> fec_ultact { get; set; }
        public bool status_usr { get; set; }
    
        public virtual ICollection<otsemov> otsemov { get; set; }
        public virtual ICollection<otsemov> otsemov1 { get; set; }
        public virtual ICollection<rolesxUsr> rolesxUsr { get; set; }
    }
}
